import random
import string

NAMES_BY_COUNTRY = {
    'US': {
        'first_m': ['James','John','Robert','Michael','William','David','Richard','Joseph','Thomas','Charles','Christopher','Daniel','Matthew','Anthony','Mark','Steven','Andrew','Joshua','Kenneth','Kevin','Brian','George','Timothy','Ronald','Edward','Jason','Jeffrey','Ryan','Jacob','Nicholas'],
        'first_f': ['Mary','Patricia','Jennifer','Linda','Barbara','Elizabeth','Susan','Jessica','Sarah','Karen','Lisa','Nancy','Betty','Margaret','Sandra','Ashley','Dorothy','Kimberly','Emily','Donna','Michelle','Carol','Amanda','Melissa','Deborah','Stephanie','Rebecca','Sharon','Laura','Cynthia'],
        'last': ['Smith','Johnson','Williams','Brown','Jones','Garcia','Miller','Davis','Rodriguez','Martinez','Hernandez','Lopez','Gonzalez','Wilson','Anderson','Thomas','Taylor','Moore','Jackson','Martin','Lee','Perez','Thompson','White','Harris','Sanchez','Clark','Ramirez','Lewis','Robinson'],
        'cities': [('New York','NY','10001'),('Los Angeles','CA','90001'),('Chicago','IL','60601'),('Houston','TX','77001'),('Phoenix','AZ','85001'),('Philadelphia','PA','19101'),('San Antonio','TX','78201'),('San Diego','CA','92101'),('Dallas','TX','75201'),('San Jose','CA','95101'),('Austin','TX','73301'),('Jacksonville','FL','32099'),('Fort Worth','TX','76101'),('Columbus','OH','43085'),('Charlotte','NC','28201')],
        'streets': ['Main St','Oak Ave','Maple Dr','Cedar Ln','Elm St','Pine Rd','Washington Blvd','Park Ave','Lake Dr','Sunset Blvd','Broadway','Highland Ave','Forest Dr','River Rd','Spring St'],
        'phone_prefix': '+1',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.com','outlook.com','hotmail.com','aol.com'],
    },
    'UK': {
        'first_m': ['Oliver','Harry','Jack','George','Noah','Charlie','Jacob','Alfie','Freddie','Oscar','Leo','Logan','Archie','Theo','Thomas','James','William','Arthur','Joshua','Henry'],
        'first_f': ['Olivia','Amelia','Isla','Ava','Emily','Sophia','Grace','Mia','Poppy','Ella','Lily','Jessica','Charlotte','Sophie','Daisy','Freya','Alice','Florence','Evelyn','Isabella'],
        'last': ['Smith','Jones','Williams','Taylor','Brown','Davies','Evans','Wilson','Thomas','Roberts','Johnson','Lewis','Walker','Robinson','Wood','Thompson','White','Watson','Jackson','Wright'],
        'cities': [('London','England','EC1A 1BB'),('Manchester','England','M1 1AA'),('Birmingham','England','B1 1AA'),('Leeds','England','LS1 1AA'),('Glasgow','Scotland','G1 1AA'),('Liverpool','England','L1 1AA'),('Bristol','England','BS1 1AA'),('Sheffield','England','S1 1AA'),('Edinburgh','Scotland','EH1 1AA'),('Cardiff','Wales','CF10 1AA')],
        'streets': ['High Street','Church Road','Station Road','Victoria Road','Park Lane','Queen Street','Kings Road','London Road','Mill Lane','Green Lane'],
        'phone_prefix': '+44',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.co.uk','outlook.com','hotmail.co.uk','btinternet.com'],
    },
    'CA': {
        'first_m': ['Liam','Noah','Oliver','William','Elijah','James','Benjamin','Lucas','Henry','Alexander'],
        'first_f': ['Olivia','Emma','Charlotte','Amelia','Ava','Sophia','Isabella','Mia','Evelyn','Harper'],
        'last': ['Smith','Brown','Tremblay','Martin','Roy','Wilson','Macdonald','Taylor','Campbell','Anderson'],
        'cities': [('Toronto','ON','M5H 2N2'),('Vancouver','BC','V6B 1A1'),('Montreal','QC','H2X 1Y4'),('Calgary','AB','T2P 1J9'),('Ottawa','ON','K1P 1J1'),('Edmonton','AB','T5J 0R1'),('Winnipeg','MB','R3C 0A1'),('Quebec City','QC','G1R 4P5')],
        'streets': ['Main Street','King Street','Queen Street','Yonge Street','Bay Street','Dundas Street','College Street','Bloor Street'],
        'phone_prefix': '+1',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.ca','outlook.com','hotmail.com'],
    },
    'AU': {
        'first_m': ['Oliver','Noah','Jack','William','Leo','Lucas','Henry','James','Liam','Ethan'],
        'first_f': ['Charlotte','Olivia','Amelia','Isla','Mia','Ava','Grace','Willow','Harper','Chloe'],
        'last': ['Smith','Jones','Williams','Brown','Wilson','Taylor','Johnson','White','Martin','Anderson'],
        'cities': [('Sydney','NSW','2000'),('Melbourne','VIC','3000'),('Brisbane','QLD','4000'),('Perth','WA','6000'),('Adelaide','SA','5000'),('Canberra','ACT','2600'),('Hobart','TAS','7000'),('Darwin','NT','0800')],
        'streets': ['George Street','King Street','High Street','Queen Street','Park Road','Station Street','Church Street','Victoria Street'],
        'phone_prefix': '+61',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com.au','outlook.com','bigpond.com'],
    },
    'DE': {
        'first_m': ['Ben','Paul','Leon','Finn','Elias','Jonas','Noah','Luis','Lukas','Felix'],
        'first_f': ['Emma','Mia','Hannah','Sophia','Emilia','Lina','Marie','Mila','Lea','Anna'],
        'last': ['Mueller','Schmidt','Schneider','Fischer','Weber','Meyer','Wagner','Becker','Schulz','Hoffmann'],
        'cities': [('Berlin','Berlin','10115'),('Munich','Bavaria','80331'),('Hamburg','Hamburg','20095'),('Frankfurt','Hesse','60311'),('Cologne','NRW','50667'),('Stuttgart','BW','70173'),('Dusseldorf','NRW','40213')],
        'streets': ['Hauptstrasse','Bahnhofstrasse','Schulstrasse','Gartenstrasse','Dorfstrasse','Bergstrasse','Kirchstrasse','Waldstrasse'],
        'phone_prefix': '+49',
        'phone_len': 10,
        'email_domains': ['gmail.com','web.de','gmx.de','t-online.de'],
    },
    'FR': {
        'first_m': ['Gabriel','Leo','Raphael','Arthur','Louis','Lucas','Adam','Jules','Hugo','Liam'],
        'first_f': ['Emma','Jade','Louise','Alice','Lina','Chloe','Rose','Lea','Anna','Mia'],
        'last': ['Martin','Bernard','Dubois','Thomas','Robert','Richard','Petit','Durand','Leroy','Moreau'],
        'cities': [('Paris','Ile-de-France','75001'),('Lyon','Auvergne','69001'),('Marseille','PACA','13001'),('Toulouse','Occitanie','31000'),('Nice','PACA','06000'),('Nantes','Loire','44000'),('Bordeaux','Nouvelle','33000')],
        'streets': ['Rue de la Paix','Rue du Commerce','Avenue des Champs','Rue Victor Hugo','Rue de la Gare','Boulevard Saint-Michel','Rue Pasteur'],
        'phone_prefix': '+33',
        'phone_len': 9,
        'email_domains': ['gmail.com','orange.fr','free.fr','laposte.net'],
    },
    'IN': {
        'first_m': ['Aarav','Vivaan','Aditya','Vihaan','Arjun','Reyansh','Sai','Arnav','Ayaan','Krishna'],
        'first_f': ['Saanvi','Aanya','Aadhya','Aaradhya','Ananya','Pari','Anika','Navya','Angel','Diya'],
        'last': ['Sharma','Verma','Gupta','Singh','Kumar','Patel','Shah','Mehta','Joshi','Reddy'],
        'cities': [('Mumbai','Maharashtra','400001'),('Delhi','Delhi','110001'),('Bangalore','Karnataka','560001'),('Hyderabad','Telangana','500001'),('Chennai','Tamil Nadu','600001'),('Kolkata','West Bengal','700001'),('Pune','Maharashtra','411001'),('Ahmedabad','Gujarat','380001')],
        'streets': ['MG Road','Station Road','Gandhi Nagar','Nehru Street','Civil Lines','Mall Road','Park Street','Lake Road'],
        'phone_prefix': '+91',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.in','rediffmail.com','outlook.com'],
    },
    'BR': {
        'first_m': ['Miguel','Arthur','Bernardo','Heitor','Davi','Lorenzo','Theo','Pedro','Gabriel','Enzo'],
        'first_f': ['Alice','Sophia','Helena','Valentina','Laura','Isabella','Manuela','Julia','Heloisa','Luiza'],
        'last': ['Silva','Santos','Oliveira','Souza','Rodrigues','Ferreira','Alves','Pereira','Lima','Gomes'],
        'cities': [('Sao Paulo','SP','01000-000'),('Rio de Janeiro','RJ','20000-000'),('Brasilia','DF','70000-000'),('Salvador','BA','40000-000'),('Fortaleza','CE','60000-000'),('Belo Horizonte','MG','30000-000')],
        'streets': ['Rua das Flores','Avenida Brasil','Rua Sao Paulo','Rua Quinze de Novembro','Avenida Paulista','Rua Augusta'],
        'phone_prefix': '+55',
        'phone_len': 11,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com.br','uol.com.br'],
    },
    'MX': {
        'first_m': ['Santiago','Mateo','Sebastian','Leonardo','Matias','Emiliano','Diego','Miguel','Daniel','Alejandro'],
        'first_f': ['Sofia','Valentina','Regina','Camila','Maria','Fernanda','Renata','Victoria','Mariana','Ximena'],
        'last': ['Garcia','Rodriguez','Martinez','Lopez','Hernandez','Gonzalez','Perez','Sanchez','Ramirez','Torres'],
        'cities': [('Mexico City','CDMX','06000'),('Guadalajara','Jalisco','44100'),('Monterrey','Nuevo Leon','64000'),('Puebla','Puebla','72000'),('Cancun','Quintana Roo','77500'),('Merida','Yucatan','97000')],
        'streets': ['Avenida Reforma','Calle Hidalgo','Avenida Juarez','Calle Morelos','Avenida Insurgentes','Calle 5 de Mayo'],
        'phone_prefix': '+52',
        'phone_len': 10,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com.mx','outlook.com'],
    },
    'JP': {
        'first_m': ['Haruto','Yuto','Sota','Hinata','Riku','Minato','Kaito','Asahi','Ren','Yuki'],
        'first_f': ['Himari','Hina','Yua','Sakura','Ichika','Akari','Sara','Yui','Rin','Mei'],
        'last': ['Sato','Suzuki','Takahashi','Tanaka','Watanabe','Ito','Yamamoto','Nakamura','Kobayashi','Kato'],
        'cities': [('Tokyo','Tokyo','100-0001'),('Osaka','Osaka','530-0001'),('Yokohama','Kanagawa','220-0001'),('Nagoya','Aichi','450-0001'),('Sapporo','Hokkaido','060-0001'),('Kyoto','Kyoto','600-8001')],
        'streets': ['1-chome','2-chome','3-chome','4-chome','5-chome'],
        'phone_prefix': '+81',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.co.jp','docomo.ne.jp','softbank.ne.jp'],
    },
    'IT': {
        'first_m': ['Leonardo','Francesco','Alessandro','Lorenzo','Mattia','Andrea','Gabriele','Riccardo','Tommaso','Edoardo'],
        'first_f': ['Sofia','Aurora','Giulia','Ginevra','Alice','Emma','Giorgia','Greta','Beatrice','Anna'],
        'last': ['Rossi','Russo','Ferrari','Esposito','Bianchi','Romano','Colombo','Ricci','Marino','Greco'],
        'cities': [('Rome','Lazio','00100'),('Milan','Lombardy','20121'),('Naples','Campania','80100'),('Turin','Piedmont','10121'),('Florence','Tuscany','50121'),('Venice','Veneto','30121')],
        'streets': ['Via Roma','Via Garibaldi','Via Mazzini','Via Dante','Via Verdi','Corso Italia','Via Nazionale'],
        'phone_prefix': '+39',
        'phone_len': 10,
        'email_domains': ['gmail.com','libero.it','virgilio.it','tiscali.it'],
    },
    'ES': {
        'first_m': ['Hugo','Martin','Lucas','Mateo','Leo','Daniel','Alejandro','Manuel','Pablo','Adrian'],
        'first_f': ['Lucia','Sofia','Maria','Martina','Paula','Julia','Daniela','Valeria','Alba','Emma'],
        'last': ['Garcia','Rodriguez','Martinez','Lopez','Sanchez','Gonzalez','Hernandez','Perez','Fernandez','Gomez'],
        'cities': [('Madrid','Madrid','28001'),('Barcelona','Catalonia','08001'),('Valencia','Valencia','46001'),('Seville','Andalusia','41001'),('Bilbao','Basque','48001'),('Malaga','Andalusia','29001')],
        'streets': ['Calle Mayor','Gran Via','Calle Real','Paseo de la Castellana','Avenida de la Constitucion','Calle Nueva'],
        'phone_prefix': '+34',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.es','yahoo.es','outlook.es'],
    },
    'KR': {
        'first_m': ['Minho','Jimin','Seongjin','Jungwoo','Hyunwoo','Donghyun','Seojun','Jihoon','Taehyung','Yoongi'],
        'first_f': ['Jiyeon','Soeun','Yuna','Minji','Subin','Hayoon','Dahyun','Chaeyoung','Nayeon','Sana'],
        'last': ['Kim','Lee','Park','Choi','Jung','Kang','Cho','Yoon','Jang','Lim'],
        'cities': [('Seoul','Seoul','06236'),('Busan','Busan','48058'),('Incheon','Incheon','21554'),('Daegu','Daegu','41585'),('Daejeon','Daejeon','35242'),('Gwangju','Gwangju','61945'),('Suwon','Gyeonggi','16490')],
        'streets': ['Gangnam-daero','Teheran-ro','Sejong-daero','Eulji-ro','Dongdaemun-ro','Jongno','Hangang-daero'],
        'phone_prefix': '+82',
        'phone_len': 10,
        'email_domains': ['gmail.com','naver.com','daum.net','hanmail.net'],
    },
    'ID': {
        'first_m': ['Budi','Agus','Hendra','Rizky','Dimas','Andi','Fajar','Arief','Bagus','Dwi'],
        'first_f': ['Siti','Dewi','Putri','Ayu','Rina','Wulan','Indah','Sri','Nurul','Fitri'],
        'last': ['Wijaya','Susanto','Pratama','Setiawan','Hidayat','Kurniawan','Santoso','Putra','Saputra','Wibowo'],
        'cities': [('Jakarta','DKI Jakarta','10110'),('Surabaya','Jawa Timur','60271'),('Bandung','Jawa Barat','40111'),('Medan','Sumatera Utara','20111'),('Semarang','Jawa Tengah','50131'),('Makassar','Sulawesi Selatan','90111'),('Yogyakarta','DI Yogyakarta','55211')],
        'streets': ['Jalan Sudirman','Jalan Thamrin','Jalan Gatot Subroto','Jalan Merdeka','Jalan Ahmad Yani','Jalan Diponegoro','Jalan Imam Bonjol'],
        'phone_prefix': '+62',
        'phone_len': 11,
        'email_domains': ['gmail.com','yahoo.co.id','outlook.com','hotmail.com'],
    },
    'MY': {
        'first_m': ['Ahmad','Muhammad','Mohd','Abdul','Ali','Haziq','Amir','Faiz','Hafiz','Zul'],
        'first_f': ['Nur','Siti','Aisyah','Fatimah','Nadia','Aini','Syafiqah','Zara','Liyana','Amira'],
        'last': ['Abdullah','Ibrahim','Rahman','Hassan','Ismail','Ahmad','Ali','Yusof','Omar','Salleh'],
        'cities': [('Kuala Lumpur','WP KL','50000'),('George Town','Penang','10000'),('Johor Bahru','Johor','80000'),('Ipoh','Perak','30000'),('Shah Alam','Selangor','40000'),('Kota Kinabalu','Sabah','88000'),('Kuching','Sarawak','93000')],
        'streets': ['Jalan Bukit Bintang','Jalan Sultan Ismail','Jalan Ampang','Jalan Tuanku Abdul Rahman','Jalan Masjid India','Jalan Imbi','Jalan Raja Chulan'],
        'phone_prefix': '+60',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'SG': {
        'first_m': ['Wei','Jun','Jia','Yi','Zhi','Hao','Ming','Kai','Xuan','Rui'],
        'first_f': ['Hui','Xin','Ying','Ling','Mei','Yan','Fang','Li','Jing','Yun'],
        'last': ['Tan','Lim','Lee','Ng','Ong','Wong','Goh','Chua','Chan','Koh'],
        'cities': [('Singapore','Central','018956'),('Singapore','Jurong','609731'),('Singapore','Tampines','528523'),('Singapore','Woodlands','730001'),('Singapore','Bedok','460001'),('Singapore','Ang Mo Kio','560001')],
        'streets': ['Orchard Road','Raffles Place','Marina Boulevard','Shenton Way','Cecil Street','Robinson Road','Bukit Timah Road'],
        'phone_prefix': '+65',
        'phone_len': 8,
        'email_domains': ['gmail.com','yahoo.com.sg','hotmail.com','outlook.sg'],
    },
    'TH': {
        'first_m': ['Somchai','Somsak','Prasert','Wichai','Supachai','Kittisak','Nattapong','Piyawat','Tanakorn','Anuwat'],
        'first_f': ['Siriwan','Nattaya','Ploy','Praew','Fah','Nan','Pim','Kwan','Nong','Dao'],
        'last': ['Srisai','Saetang','Bunmi','Jaidee','Meesuk','Phongphan','Rattanakul','Wongsa','Thongkam','Suksan'],
        'cities': [('Bangkok','Bangkok','10100'),('Chiang Mai','Chiang Mai','50000'),('Phuket','Phuket','83000'),('Pattaya','Chonburi','20150'),('Nonthaburi','Nonthaburi','11000'),('Hat Yai','Songkhla','90110')],
        'streets': ['Sukhumvit Road','Silom Road','Sathorn Road','Ratchadaphisek Road','Phahonyothin Road','Rama IV Road','Charoen Krung Road'],
        'phone_prefix': '+66',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.com','yahoo.co.th','outlook.com'],
    },
    'PH': {
        'first_m': ['Juan','Jose','Mark','John','James','Michael','Angelo','Patrick','Carlo','Rafael'],
        'first_f': ['Maria','Ana','Grace','Joy','Angel','Princess','Rose','Mae','Nicole','Jasmine'],
        'last': ['Santos','Reyes','Cruz','Bautista','Dela Cruz','Garcia','Mendoza','Torres','Villanueva','Ramos'],
        'cities': [('Manila','Metro Manila','1000'),('Quezon City','Metro Manila','1100'),('Cebu City','Cebu','6000'),('Davao City','Davao','8000'),('Makati','Metro Manila','1200'),('Pasig','Metro Manila','1600')],
        'streets': ['EDSA','Roxas Boulevard','Ayala Avenue','Taft Avenue','Quezon Avenue','Commonwealth Avenue','C5 Road'],
        'phone_prefix': '+63',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.com','outlook.com','hotmail.com'],
    },
    'TW': {
        'first_m': ['Wei','Ming','Jia','Yi','Zhi','Hao','Jun','Kai','Cheng','Yu'],
        'first_f': ['Mei','Xin','Hui','Ying','Ling','Ya','Fang','Jing','Li','Yan'],
        'last': ['Chen','Lin','Huang','Zhang','Li','Wang','Wu','Liu','Cai','Yang'],
        'cities': [('Taipei','Taipei','100'),('Kaohsiung','Kaohsiung','800'),('Taichung','Taichung','400'),('Tainan','Tainan','700'),('Hsinchu','Hsinchu','300'),('Taoyuan','Taoyuan','330')],
        'streets': ['Zhongxiao East Road','Xinyi Road','Ren\'ai Road','Nanjing East Road','Dunhua South Road','Fuxing South Road'],
        'phone_prefix': '+886',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com.tw','hotmail.com','pchome.com.tw'],
    },
    'VN': {
        'first_m': ['Minh','Duc','Huy','Khoa','Tuan','Nam','Long','Phuc','Duy','Thanh'],
        'first_f': ['Linh','Trang','Anh','Huong','Thao','Mai','Ngoc','Hanh','Lan','Phuong'],
        'last': ['Nguyen','Tran','Le','Pham','Hoang','Vo','Dang','Bui','Do','Ngo'],
        'cities': [('Ho Chi Minh City','HCMC','700000'),('Hanoi','Hanoi','100000'),('Da Nang','Da Nang','550000'),('Hai Phong','Hai Phong','180000'),('Can Tho','Can Tho','900000'),('Nha Trang','Khanh Hoa','650000')],
        'streets': ['Nguyen Hue','Le Loi','Dong Khoi','Tran Hung Dao','Hai Ba Trung','Vo Van Tan','Nam Ky Khoi Nghia'],
        'phone_prefix': '+84',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com.vn','outlook.com','hotmail.com'],
    },
    'HK': {
        'first_m': ['Ka','Chi','Wai','Ho','Tsz','Lok','Hei','Siu','Man','Kin'],
        'first_f': ['Wing','Ka','Hoi','Yee','Tsz','Sze','Wai','Man','Yan','Sum'],
        'last': ['Chan','Wong','Leung','Lau','Cheung','Li','Ng','Ho','Tam','Kwok'],
        'cities': [('Hong Kong','Central','999077'),('Kowloon','Kowloon','999077'),('Tsim Sha Tsui','Kowloon','999077'),('Wan Chai','Hong Kong Island','999077'),('Mong Kok','Kowloon','999077'),('Causeway Bay','Hong Kong Island','999077')],
        'streets': ['Nathan Road','Queens Road','Des Voeux Road','Hennessy Road','Canton Road','Argyle Street','Chatham Road'],
        'phone_prefix': '+852',
        'phone_len': 8,
        'email_domains': ['gmail.com','yahoo.com.hk','hotmail.com','outlook.com'],
    },
    'NZ': {
        'first_m': ['Liam','Oliver','Noah','James','Lucas','Jack','William','Benjamin','Leo','Mason'],
        'first_f': ['Charlotte','Olivia','Amelia','Isla','Ava','Mia','Grace','Harper','Ella','Willow'],
        'last': ['Smith','Williams','Brown','Wilson','Taylor','Anderson','Thomas','Harris','Martin','Thompson'],
        'cities': [('Auckland','Auckland','1010'),('Wellington','Wellington','6011'),('Christchurch','Canterbury','8011'),('Hamilton','Waikato','3204'),('Tauranga','Bay of Plenty','3110'),('Dunedin','Otago','9016')],
        'streets': ['Queen Street','Lambton Quay','Colombo Street','Victoria Street','High Street','Cuba Street'],
        'phone_prefix': '+64',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.co.nz','outlook.com','xtra.co.nz'],
    },
    'SA': {
        'first_m': ['Mohammed','Ahmed','Abdullah','Khalid','Fahd','Omar','Ali','Faisal','Sultan','Nasser'],
        'first_f': ['Fatima','Aisha','Noura','Sara','Maha','Haya','Lama','Reem','Dana','Lina'],
        'last': ['Al-Saud','Al-Rashid','Al-Otaibi','Al-Ghamdi','Al-Qahtani','Al-Harbi','Al-Shehri','Al-Dosari','Al-Zahrani','Al-Malki'],
        'cities': [('Riyadh','Riyadh','11564'),('Jeddah','Makkah','21442'),('Mecca','Makkah','24231'),('Medina','Medina','42311'),('Dammam','Eastern','31446'),('Khobar','Eastern','31952')],
        'streets': ['King Fahd Road','Olaya Street','Tahlia Street','Prince Sultan Road','King Abdullah Road','Palestine Street'],
        'phone_prefix': '+966',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.sa'],
    },
    'AE': {
        'first_m': ['Mohammed','Ahmed','Ali','Omar','Khalid','Hassan','Rashid','Sultan','Saeed','Hamad'],
        'first_f': ['Fatima','Mariam','Aisha','Sara','Noura','Hessa','Moza','Latifa','Shamma','Amna'],
        'last': ['Al-Maktoum','Al-Nahyan','Al-Falasi','Al-Mansoori','Al-Hashimi','Al-Ali','Al-Suwaidi','Al-Mazrouei','Al-Ketbi','Al-Shamsi'],
        'cities': [('Dubai','Dubai','00000'),('Abu Dhabi','Abu Dhabi','00000'),('Sharjah','Sharjah','00000'),('Ajman','Ajman','00000'),('Ras Al Khaimah','RAK','00000'),('Fujairah','Fujairah','00000')],
        'streets': ['Sheikh Zayed Road','Jumeirah Beach Road','Al Wasl Road','Khalifa Street','Hamdan Street','Corniche Road'],
        'phone_prefix': '+971',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.com'],
    },
    'TR': {
        'first_m': ['Mehmet','Mustafa','Ahmet','Ali','Hasan','Huseyin','Ibrahim','Ismail','Yusuf','Osman'],
        'first_f': ['Fatma','Ayse','Emine','Hatice','Zeynep','Elif','Merve','Busra','Esra','Kubra'],
        'last': ['Yilmaz','Kaya','Demir','Celik','Sahin','Yildiz','Yildirim','Ozturk','Aydin','Ozdemir'],
        'cities': [('Istanbul','Istanbul','34000'),('Ankara','Ankara','06000'),('Izmir','Izmir','35000'),('Bursa','Bursa','16000'),('Antalya','Antalya','07000'),('Adana','Adana','01000')],
        'streets': ['Istiklal Caddesi','Bagdat Caddesi','Ataturk Bulvari','Cumhuriyet Caddesi','Fevzi Pasa Bulvari','Gazi Bulvari'],
        'phone_prefix': '+90',
        'phone_len': 10,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com.tr','outlook.com'],
    },
    'PL': {
        'first_m': ['Jan','Andrzej','Piotr','Krzysztof','Stanislaw','Tomasz','Pawel','Marcin','Michal','Marek'],
        'first_f': ['Anna','Maria','Katarzyna','Malgorzata','Agnieszka','Barbara','Ewa','Krystyna','Elzbieta','Magdalena'],
        'last': ['Nowak','Kowalski','Wisniewski','Wojciechowski','Kaminski','Lewandowski','Zielinski','Szymanski','Wozniak','Dabrowski'],
        'cities': [('Warsaw','Masovia','00-001'),('Krakow','Lesser Poland','30-001'),('Lodz','Lodz','90-001'),('Wroclaw','Lower Silesia','50-001'),('Poznan','Greater Poland','60-001'),('Gdansk','Pomerania','80-001')],
        'streets': ['Aleje Jerozolimskie','Marszalkowska','Nowy Swiat','Krakowskie Przedmiescie','Piotrkowska','Florianska'],
        'phone_prefix': '+48',
        'phone_len': 9,
        'email_domains': ['gmail.com','wp.pl','onet.pl','interia.pl'],
    },
    'NL': {
        'first_m': ['Daan','Sem','Lucas','Levi','Finn','Noah','Milan','Jesse','Lars','Luca'],
        'first_f': ['Emma','Julia','Sophie','Anna','Lisa','Saar','Eva','Noor','Lotte','Mila'],
        'last': ['De Jong','Jansen','De Vries','Van den Berg','Van Dijk','Bakker','Janssen','Visser','Smit','Meijer'],
        'cities': [('Amsterdam','North Holland','1012'),('Rotterdam','South Holland','3011'),('The Hague','South Holland','2511'),('Utrecht','Utrecht','3511'),('Eindhoven','North Brabant','5611'),('Groningen','Groningen','9711')],
        'streets': ['Kalverstraat','Leidsestraat','Dam','Coolsingel','Binnenhof','Oudegracht'],
        'phone_prefix': '+31',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.nl','outlook.nl','ziggo.nl'],
    },
    'SE': {
        'first_m': ['Oscar','William','Lucas','Liam','Oliver','Hugo','Alexander','Elias','Charlie','Noah'],
        'first_f': ['Alice','Olivia','Astrid','Maja','Vera','Ebba','Ella','Wilma','Alma','Elsa'],
        'last': ['Andersson','Johansson','Karlsson','Nilsson','Eriksson','Larsson','Olsson','Persson','Svensson','Gustafsson'],
        'cities': [('Stockholm','Stockholm','111 20'),('Gothenburg','Vastra Gotaland','411 01'),('Malmo','Skane','211 18'),('Uppsala','Uppsala','751 05'),('Linkoping','Ostergotland','581 83')],
        'streets': ['Drottninggatan','Kungsgatan','Storgatan','Sveavagen','Vasagatan','Gotgatan'],
        'phone_prefix': '+46',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.se','outlook.com','telia.com'],
    },
    'CH': {
        'first_m': ['Noah','Liam','Luca','Elias','Gabriel','Leon','David','Samuel','Julian','Matteo'],
        'first_f': ['Mia','Emma','Elena','Lea','Lara','Laura','Anna','Lina','Sara','Sofia'],
        'last': ['Mueller','Meier','Schmid','Keller','Weber','Huber','Schneider','Meyer','Steiner','Fischer'],
        'cities': [('Zurich','Zurich','8001'),('Geneva','Geneva','1201'),('Basel','Basel','4001'),('Bern','Bern','3001'),('Lausanne','Vaud','1003'),('Lucerne','Lucerne','6003')],
        'streets': ['Bahnhofstrasse','Marktgasse','Freiestrasse','Kramgasse','Rue du Rhone','Rue du Marche'],
        'phone_prefix': '+41',
        'phone_len': 9,
        'email_domains': ['gmail.com','bluewin.ch','gmx.ch','outlook.com'],
    },
    'RU': {
        'first_m': ['Alexander','Dmitry','Maxim','Sergei','Andrei','Alexei','Ivan','Mikhail','Nikita','Artem'],
        'first_f': ['Anastasia','Maria','Daria','Anna','Elizaveta','Victoria','Polina','Ekaterina','Sofia','Alina'],
        'last': ['Ivanov','Smirnov','Kuznetsov','Popov','Sokolov','Lebedev','Kozlov','Novikov','Morozov','Petrov'],
        'cities': [('Moscow','Moscow','101000'),('Saint Petersburg','SPb','190000'),('Novosibirsk','Novosibirsk','630099'),('Yekaterinburg','Sverdlovsk','620014'),('Kazan','Tatarstan','420111'),('Nizhny Novgorod','Nizhny','603001')],
        'streets': ['Tverskaya Ulitsa','Nevsky Prospekt','Arbat','Lenina Ulitsa','Mira Prospekt','Kutuzovsky Prospekt'],
        'phone_prefix': '+7',
        'phone_len': 10,
        'email_domains': ['gmail.com','mail.ru','yandex.ru','rambler.ru'],
    },
    'CN': {
        'first_m': ['Wei','Fang','Lei','Jun','Jie','Tao','Qiang','Ming','Hao','Peng'],
        'first_f': ['Fang','Xia','Juan','Li','Na','Jing','Yan','Min','Ling','Yun'],
        'last': ['Wang','Li','Zhang','Liu','Chen','Yang','Huang','Zhao','Wu','Zhou'],
        'cities': [('Beijing','Beijing','100000'),('Shanghai','Shanghai','200000'),('Guangzhou','Guangdong','510000'),('Shenzhen','Guangdong','518000'),('Chengdu','Sichuan','610000'),('Hangzhou','Zhejiang','310000')],
        'streets': ['Nanjing Road','Wangfujing','Chang\'an Avenue','Huaihai Road','Zhongshan Road','Jiefang Road'],
        'phone_prefix': '+86',
        'phone_len': 11,
        'email_domains': ['gmail.com','163.com','qq.com','126.com','sina.com'],
    },
    'AR': {
        'first_m': ['Santiago','Mateo','Benjamin','Thiago','Santino','Bautista','Juan','Felipe','Lorenzo','Valentino'],
        'first_f': ['Sofia','Isabella','Emma','Valentina','Mia','Catalina','Martina','Alma','Olivia','Emilia'],
        'last': ['Garcia','Rodriguez','Martinez','Lopez','Gonzalez','Fernandez','Perez','Sanchez','Ramirez','Torres'],
        'cities': [('Buenos Aires','CABA','C1001'),('Cordoba','Cordoba','X5000'),('Rosario','Santa Fe','S2000'),('Mendoza','Mendoza','M5500'),('La Plata','Buenos Aires','B1900'),('Tucuman','Tucuman','T4000')],
        'streets': ['Avenida 9 de Julio','Calle Florida','Avenida Corrientes','Avenida Santa Fe','Calle Rivadavia','Avenida de Mayo'],
        'phone_prefix': '+54',
        'phone_len': 10,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com.ar','outlook.com'],
    },
    'AT': {
        'first_m': ['Lukas','Tobias','David','Maximilian','Felix','Sebastian','Paul','Alexander','Julian','Simon'],
        'first_f': ['Anna','Laura','Sarah','Julia','Lisa','Lena','Hannah','Katharina','Sophie','Marie'],
        'last': ['Gruber','Huber','Bauer','Wagner','Mueller','Pichler','Steiner','Moser','Mayer','Hofer'],
        'cities': [('Vienna','Vienna','1010'),('Graz','Styria','8010'),('Linz','Upper Austria','4020'),('Salzburg','Salzburg','5020'),('Innsbruck','Tyrol','6020'),('Klagenfurt','Carinthia','9020')],
        'streets': ['Mariahilfer Strasse','Karntner Strasse','Graben','Landstrasse','Hauptplatz','Bahnhofstrasse'],
        'phone_prefix': '+43',
        'phone_len': 10,
        'email_domains': ['gmail.com','gmx.at','outlook.com','a1.net'],
    },
    'BE': {
        'first_m': ['Lucas','Noah','Liam','Louis','Arthur','Jules','Victor','Adam','Mohamed','Alexander'],
        'first_f': ['Emma','Louise','Olivia','Mila','Alice','Charlotte','Lina','Marie','Elena','Noor'],
        'last': ['Peeters','Janssens','Maes','Jacobs','Willems','Claes','Mertens','Goossens','Wouters','De Smedt'],
        'cities': [('Brussels','Brussels','1000'),('Antwerp','Flanders','2000'),('Ghent','Flanders','9000'),('Bruges','Flanders','8000'),('Liege','Wallonia','4000'),('Namur','Wallonia','5000')],
        'streets': ['Meir','Veldstraat','Rue Neuve','Grand Place','Lippenslaan','Bondgenotenlaan'],
        'phone_prefix': '+32',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.be','outlook.be','telenet.be'],
    },
    'PT': {
        'first_m': ['Joao','Francisco','Santiago','Rodrigo','Tomas','Martim','Afonso','Guilherme','Miguel','Diogo'],
        'first_f': ['Maria','Leonor','Matilde','Beatriz','Carolina','Mariana','Ana','Ines','Sofia','Francisca'],
        'last': ['Silva','Santos','Ferreira','Pereira','Oliveira','Costa','Rodrigues','Martins','Jesus','Sousa'],
        'cities': [('Lisbon','Lisbon','1000-001'),('Porto','Porto','4000-001'),('Braga','Braga','4700-001'),('Coimbra','Coimbra','3000-001'),('Faro','Faro','8000-001'),('Funchal','Madeira','9000-001')],
        'streets': ['Rua Augusta','Avenida da Liberdade','Rua de Santa Catarina','Rua dos Clerigos','Praca do Comercio','Rua Garrett'],
        'phone_prefix': '+351',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.com','sapo.pt','outlook.pt'],
    },
    'IE': {
        'first_m': ['Jack','James','Noah','Daniel','Conor','Sean','Adam','Liam','Luke','Aaron'],
        'first_f': ['Emily','Sophie','Emma','Grace','Aoife','Ciara','Niamh','Sarah','Chloe','Ava'],
        'last': ['Murphy','Kelly','O\'Sullivan','Walsh','Smith','O\'Brien','Byrne','Ryan','O\'Connor','O\'Neill'],
        'cities': [('Dublin','Leinster','D01'),('Cork','Munster','T12'),('Galway','Connacht','H91'),('Limerick','Munster','V94'),('Waterford','Munster','X91'),('Kilkenny','Leinster','R95')],
        'streets': ['O\'Connell Street','Grafton Street','Henry Street','Patrick Street','Shop Street','High Street'],
        'phone_prefix': '+353',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.ie','outlook.com','eircom.net'],
    },
    'DK': {
        'first_m': ['William','Oscar','Noah','Lucas','Victor','Oliver','Carl','Frederik','Malthe','Emil'],
        'first_f': ['Alma','Ida','Emma','Ella','Sofia','Freja','Clara','Anna','Josephine','Nora'],
        'last': ['Nielsen','Jensen','Hansen','Pedersen','Andersen','Christensen','Larsen','Sorensen','Rasmussen','Jorgensen'],
        'cities': [('Copenhagen','Hovedstaden','1050'),('Aarhus','Midtjylland','8000'),('Odense','Syddanmark','5000'),('Aalborg','Nordjylland','9000'),('Esbjerg','Syddanmark','6700'),('Randers','Midtjylland','8900')],
        'streets': ['Stroget','Vestergade','Norregade','Ostergade','Algade','Sondergade'],
        'phone_prefix': '+45',
        'phone_len': 8,
        'email_domains': ['gmail.com','hotmail.dk','outlook.dk','jubii.dk'],
    },
    'NO': {
        'first_m': ['William','Noah','Oliver','Emil','Liam','Jakob','Lucas','Filip','Oskar','Henrik'],
        'first_f': ['Emma','Nora','Ella','Olivia','Maja','Sofie','Ingrid','Sara','Emilie','Ida'],
        'last': ['Hansen','Johansen','Olsen','Larsen','Andersen','Pedersen','Nilsen','Kristiansen','Karlsen','Johnsen'],
        'cities': [('Oslo','Oslo','0150'),('Bergen','Vestland','5003'),('Trondheim','Trondelag','7010'),('Stavanger','Rogaland','4006'),('Drammen','Viken','3015'),('Tromso','Troms','9008')],
        'streets': ['Karl Johans gate','Storgata','Torggata','Markveien','Bryggen','Kirkegata'],
        'phone_prefix': '+47',
        'phone_len': 8,
        'email_domains': ['gmail.com','hotmail.no','outlook.com','online.no'],
    },
    'FI': {
        'first_m': ['Onni','Elias','Leo','Vaino','Noel','Oliver','Eino','Eeli','Veeti','Leevi'],
        'first_f': ['Aino','Eevi','Emma','Sofia','Lilja','Helmi','Ella','Venla','Aada','Olivia'],
        'last': ['Korhonen','Virtanen','Makinen','Nieminen','Makela','Hamalainen','Laine','Heikkinen','Koskinen','Jarvinen'],
        'cities': [('Helsinki','Uusimaa','00100'),('Espoo','Uusimaa','02100'),('Tampere','Pirkanmaa','33100'),('Turku','Varsinais-Suomi','20100'),('Oulu','Pohjois-Pohjanmaa','90100'),('Jyvaskyla','Keski-Suomi','40100')],
        'streets': ['Mannerheimintie','Aleksanterinkatu','Hameenkatu','Kauppakatu','Keskuskatu','Linnankatu'],
        'phone_prefix': '+358',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.fi','outlook.com','elisa.fi'],
    },
    'CZ': {
        'first_m': ['Jan','Jakub','Tomas','Adam','Matej','Filip','Vojtech','Lukas','Martin','David'],
        'first_f': ['Eliska','Anna','Tereza','Adela','Karolina','Barbora','Viktorie','Natalie','Kristyna','Lucie'],
        'last': ['Novak','Svoboda','Novotny','Dvorak','Cerny','Prochazka','Kucera','Vesely','Horak','Nemec'],
        'cities': [('Prague','Prague','110 00'),('Brno','South Moravia','602 00'),('Ostrava','Moravia-Silesia','702 00'),('Plzen','Plzen','301 00'),('Liberec','Liberec','460 01'),('Olomouc','Olomouc','779 00')],
        'streets': ['Vaclavske namesti','Narodni trida','Vodickova','Na Prikope','Celetna','Karlova'],
        'phone_prefix': '+420',
        'phone_len': 9,
        'email_domains': ['gmail.com','seznam.cz','centrum.cz','email.cz'],
    },
    'CL': {
        'first_m': ['Benjamin','Agustin','Vicente','Martin','Matias','Joaquin','Tomas','Sebastian','Maximiliano','Nicolas'],
        'first_f': ['Sofia','Martina','Florencia','Valentina','Isidora','Agustina','Catalina','Antonella','Emilia','Fernanda'],
        'last': ['Gonzalez','Munoz','Rojas','Diaz','Perez','Soto','Contreras','Silva','Martinez','Sepulveda'],
        'cities': [('Santiago','RM','8320000'),('Valparaiso','Valparaiso','2340000'),('Concepcion','Biobio','4030000'),('Antofagasta','Antofagasta','1240000'),('Temuco','Araucania','4780000'),('Vina del Mar','Valparaiso','2520000')],
        'streets': ['Avenida Libertador','Calle Ahumada','Paseo Huerfanos','Avenida Providencia','Calle Estado','Calle Bandera'],
        'phone_prefix': '+56',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.cl'],
    },
    'CO': {
        'first_m': ['Santiago','Samuel','Nicolas','Alejandro','Sebastian','Matias','Daniel','Emiliano','Juan','Andres'],
        'first_f': ['Valentina','Sofia','Isabella','Mariana','Gabriela','Sara','Daniela','Luciana','Camila','Salome'],
        'last': ['Rodriguez','Garcia','Martinez','Lopez','Hernandez','Gonzalez','Ramirez','Torres','Diaz','Morales'],
        'cities': [('Bogota','Cundinamarca','110111'),('Medellin','Antioquia','050001'),('Cali','Valle del Cauca','760001'),('Barranquilla','Atlantico','080001'),('Cartagena','Bolivar','130001'),('Bucaramanga','Santander','680001')],
        'streets': ['Carrera 7','Calle 80','Avenida El Dorado','Calle 72','Carrera 15','Avenida Boyaca'],
        'phone_prefix': '+57',
        'phone_len': 10,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.com'],
    },
    'PE': {
        'first_m': ['Santiago','Mateo','Sebastian','Leonardo','Nicolas','Rodrigo','Diego','Alejandro','Gabriel','Daniel'],
        'first_f': ['Valentina','Camila','Luciana','Sofia','Isabella','Mariana','Victoria','Daniela','Ariana','Fernanda'],
        'last': ['Garcia','Rodriguez','Martinez','Lopez','Gonzalez','Flores','Chavez','Rojas','Torres','Vasquez'],
        'cities': [('Lima','Lima','15001'),('Arequipa','Arequipa','04001'),('Trujillo','La Libertad','13001'),('Cusco','Cusco','08001'),('Chiclayo','Lambayeque','14001'),('Piura','Piura','20001')],
        'streets': ['Avenida Arequipa','Jirón de la Union','Avenida Larco','Calle Lima','Avenida Grau','Avenida Brasil'],
        'phone_prefix': '+51',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.com'],
    },
    'ZA': {
        'first_m': ['Liam','Junior','Blessing','Bandile','Thabo','Sipho','Kabelo','Tumelo','Andile','Jason'],
        'first_f': ['Amahle','Minenhle','Lesedi','Rethabile','Amogelang','Kayla','Zara','Naledi','Thandeka','Lerato'],
        'last': ['Nkosi','Dlamini','Ndlovu','Zulu','Khumalo','Mthembu','Govender','Pillay','Botha','Van der Merwe'],
        'cities': [('Johannesburg','Gauteng','2001'),('Cape Town','Western Cape','8001'),('Durban','KwaZulu-Natal','4001'),('Pretoria','Gauteng','0001'),('Port Elizabeth','Eastern Cape','6001'),('Bloemfontein','Free State','9301')],
        'streets': ['Long Street','Adderley Street','Rivonia Road','Jan Smuts Avenue','Sandton Drive','Main Road'],
        'phone_prefix': '+27',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','outlook.com','webmail.co.za'],
    },
    'NG': {
        'first_m': ['Chukwuemeka','Oluwaseun','Adebayo','Chibueze','Olumide','Tunde','Emeka','Ikenna','Obinna','Segun'],
        'first_f': ['Chidinma','Ngozi','Adaeze','Oluwabunmi','Funmi','Yetunde','Chiamaka','Ifeoma','Blessing','Amara'],
        'last': ['Okafor','Adeyemi','Ibrahim','Obi','Eze','Balogun','Abubakar','Nwosu','Adebayo','Oluwole'],
        'cities': [('Lagos','Lagos','100001'),('Abuja','FCT','900001'),('Kano','Kano','700001'),('Ibadan','Oyo','200001'),('Port Harcourt','Rivers','500001'),('Benin City','Edo','300001')],
        'streets': ['Broad Street','Marina','Adeola Odeku Street','Allen Avenue','Awolowo Road','Herbert Macaulay Way'],
        'phone_prefix': '+234',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'EG': {
        'first_m': ['Ahmed','Mohamed','Mahmoud','Ali','Omar','Hassan','Youssef','Ibrahim','Khaled','Mostafa'],
        'first_f': ['Fatima','Nour','Sara','Mariam','Yasmin','Hana','Aya','Salma','Dina','Rania'],
        'last': ['Mohamed','Ahmed','Ali','Hassan','Ibrahim','Mahmoud','Abdel','El-Sayed','Khalil','Farouk'],
        'cities': [('Cairo','Cairo','11511'),('Alexandria','Alexandria','21500'),('Giza','Giza','12511'),('Luxor','Luxor','85951'),('Aswan','Aswan','81511'),('Port Said','Port Said','42511')],
        'streets': ['Sharia Tahrir','Sharia Qasr El-Nil','Corniche El-Nil','Sharia 26 July','Sharia Ramses','Sharia Salah Salem'],
        'phone_prefix': '+20',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'IL': {
        'first_m': ['David','Noam','Uri','Yoav','Itai','Eitan','Omer','Lavi','Ariel','Daniel'],
        'first_f': ['Noa','Tamar','Yael','Maya','Shira','Avigail','Adel','Liel','Roni','Talia'],
        'last': ['Cohen','Levi','Mizrahi','Peretz','Biton','Dahan','Avraham','Friedman','Malka','Azulay'],
        'cities': [('Tel Aviv','Tel Aviv','6100001'),('Jerusalem','Jerusalem','9100001'),('Haifa','Haifa','3100001'),('Rishon LeZion','Central','7510001'),('Petah Tikva','Central','4910001'),('Beersheba','South','8410001')],
        'streets': ['Rothschild Boulevard','Dizengoff Street','Ben Yehuda Street','Allenby Street','King George Street','Herzl Street'],
        'phone_prefix': '+972',
        'phone_len': 9,
        'email_domains': ['gmail.com','walla.co.il','hotmail.com','outlook.com'],
    },
    'GR': {
        'first_m': ['Georgios','Dimitrios','Konstantinos','Ioannis','Nikolaos','Panagiotis','Christos','Athanasios','Vasileios','Alexandros'],
        'first_f': ['Maria','Eleni','Aikaterini','Vasiliki','Sofia','Angeliki','Georgia','Dimitra','Eirini','Panagiota'],
        'last': ['Papadopoulos','Vlahos','Karamanlis','Nikolaidis','Georgiou','Pappas','Economou','Alexiou','Christodoulou','Konstantinou'],
        'cities': [('Athens','Attica','10431'),('Thessaloniki','Central Macedonia','54621'),('Patras','Western Greece','26221'),('Heraklion','Crete','71201'),('Larissa','Thessaly','41221'),('Volos','Thessaly','38221')],
        'streets': ['Ermou','Stadiou','Panepistimiou','Vassilissis Sofias','Kifissias','Syngrou'],
        'phone_prefix': '+30',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.gr','hotmail.gr','outlook.com'],
    },
    'RO': {
        'first_m': ['Alexandru','Andrei','David','Stefan','Gabriel','Daniel','Mihai','Marian','Cristian','Florin'],
        'first_f': ['Maria','Elena','Ana','Andreea','Ioana','Alexandra','Cristina','Gabriela','Mihaela','Diana'],
        'last': ['Popa','Popescu','Ionescu','Dumitru','Stan','Stoica','Gheorghe','Rusu','Munteanu','Matei'],
        'cities': [('Bucharest','Bucharest','010011'),('Cluj-Napoca','Cluj','400001'),('Timisoara','Timis','300001'),('Iasi','Iasi','700001'),('Constanta','Constanta','900001'),('Brasov','Brasov','500001')],
        'streets': ['Calea Victoriei','Bulevardul Unirii','Strada Lipscani','Bulevardul Magheru','Strada Smardan','Bulevardul Eroilor'],
        'phone_prefix': '+40',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'HU': {
        'first_m': ['Bence','Mate','Levente','Dominik','Adam','Mark','Balazs','Daniel','David','Milan'],
        'first_f': ['Hanna','Anna','Luca','Emma','Zsofia','Boglarka','Lili','Reka','Petra','Nora'],
        'last': ['Nagy','Kovacs','Toth','Szabo','Horvath','Varga','Kiss','Molnar','Nemeth','Farkas'],
        'cities': [('Budapest','Budapest','1011'),('Debrecen','Hajdu-Bihar','4024'),('Szeged','Csongrad','6720'),('Miskolc','Borsod','3525'),('Pecs','Baranya','7621'),('Gyor','Gyor-Moson','9021')],
        'streets': ['Vaci utca','Andrassy ut','Rakoczi ut','Baross utca','Kossuth Lajos utca','Deák Ferenc utca'],
        'phone_prefix': '+36',
        'phone_len': 9,
        'email_domains': ['gmail.com','freemail.hu','citromail.hu','hotmail.com'],
    },
    'UA': {
        'first_m': ['Oleksandr','Dmytro','Maksym','Artem','Bohdan','Mykola','Ivan','Vladyslav','Andriy','Taras'],
        'first_f': ['Anastasia','Sofia','Maria','Viktoria','Daryna','Alina','Olena','Yulia','Anna','Kateryna'],
        'last': ['Shevchenko','Bondarenko','Kovalenko','Tkachenko','Kravchenko','Boyko','Lysenko','Melnyk','Ponomarenko','Savchenko'],
        'cities': [('Kyiv','Kyiv','01001'),('Kharkiv','Kharkiv','61001'),('Odesa','Odesa','65001'),('Dnipro','Dnipro','49000'),('Lviv','Lviv','79000'),('Zaporizhzhia','Zaporizhzhia','69000')],
        'streets': ['Khreshchatyk','Prospekt Svobody','Deribasivska','Sumska','Shevchenka','Hrushevskoho'],
        'phone_prefix': '+380',
        'phone_len': 9,
        'email_domains': ['gmail.com','ukr.net','i.ua','meta.ua'],
    },
    'HR': {
        'first_m': ['Luka','Ivan','Marko','Mateo','David','Josip','Filip','Leon','Antonio','Borna'],
        'first_f': ['Ana','Mia','Lucija','Petra','Sara','Lana','Ena','Ema','Nika','Maja'],
        'last': ['Horvat','Kovacevic','Babic','Maric','Juric','Novak','Knezevic','Vukovic','Markovic','Matic'],
        'cities': [('Zagreb','Zagreb','10000'),('Split','Split-Dalmatia','21000'),('Rijeka','Primorje-Gorski','51000'),('Osijek','Osijek-Baranja','31000'),('Zadar','Zadar','23000'),('Dubrovnik','Dubrovnik-Neretva','20000')],
        'streets': ['Ilica','Frankopanska','Dioklecijanova','Korzo','Kalelarga','Stradun'],
        'phone_prefix': '+385',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'BG': {
        'first_m': ['Georgi','Ivan','Dimitar','Nikolay','Aleksandar','Petar','Martin','Todor','Stefan','Viktor'],
        'first_f': ['Maria','Ivanka','Elena','Viktoria','Daniela','Petya','Sofia','Gergana','Desislava','Tsvetana'],
        'last': ['Ivanov','Georgiev','Dimitrov','Petrov','Nikolov','Hristov','Todorov','Stoyanov','Angelov','Markov'],
        'cities': [('Sofia','Sofia','1000'),('Plovdiv','Plovdiv','4000'),('Varna','Varna','9000'),('Burgas','Burgas','8000'),('Ruse','Ruse','7000'),('Stara Zagora','Stara Zagora','6000')],
        'streets': ['Vitosha Boulevard','Aleksandrovska','Knyaz Boris I','Slavyanska','Han Krum','Tsar Osvoboditel'],
        'phone_prefix': '+359',
        'phone_len': 9,
        'email_domains': ['gmail.com','abv.bg','mail.bg','yahoo.com'],
    },
    'SK': {
        'first_m': ['Jakub','Adam','Samuel','Lukas','Martin','Tomas','Filip','David','Oliver','Simon'],
        'first_f': ['Sofia','Nina','Emma','Hana','Ema','Natalia','Laura','Simona','Lucia','Michaela'],
        'last': ['Horvath','Kovac','Varga','Toth','Nagy','Balaz','Molnar','Kral','Polak','Novak'],
        'cities': [('Bratislava','Bratislava','811 01'),('Kosice','Kosice','040 01'),('Presov','Presov','080 01'),('Zilina','Zilina','010 01'),('Nitra','Nitra','949 01'),('Banska Bystrica','Banska Bystrica','974 01')],
        'streets': ['Obchodna','Hlavna','Stefanikova','Hviezdoslavovo namestie','Laurinska','Panska'],
        'phone_prefix': '+421',
        'phone_len': 9,
        'email_domains': ['gmail.com','azet.sk','centrum.sk','outlook.com'],
    },
    'RS': {
        'first_m': ['Luka','Stefan','Nikola','Aleksandar','Marko','Dusan','Petar','Jovan','Filip','Nemanja'],
        'first_f': ['Ana','Milica','Mina','Teodora','Jovana','Sara','Katarina','Jelena','Dunja','Sofija'],
        'last': ['Jovanovic','Petrovic','Nikolic','Djordjevic','Stojanovic','Ilic','Markovic','Popovic','Milosevic','Stankovic'],
        'cities': [('Belgrade','Belgrade','11000'),('Novi Sad','Vojvodina','21000'),('Nis','Nisava','18000'),('Kragujevac','Sumadija','34000'),('Subotica','Vojvodina','24000'),('Zrenjanin','Vojvodina','23000')],
        'streets': ['Knez Mihailova','Terazije','Bulevar Oslobodjenja','Zmaj Jovina','Kralja Petra','Nemanjina'],
        'phone_prefix': '+381',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'BD': {
        'first_m': ['Rahim','Karim','Hasan','Arifin','Tanvir','Mamun','Shakil','Imran','Farhan','Rashed'],
        'first_f': ['Fatima','Nusrat','Tasnim','Afsana','Sadia','Tania','Sharmin','Nazia','Farhana','Sumaiya'],
        'last': ['Rahman','Islam','Hossain','Ahmed','Khan','Akter','Ali','Uddin','Haque','Chowdhury'],
        'cities': [('Dhaka','Dhaka','1000'),('Chittagong','Chittagong','4000'),('Khulna','Khulna','9000'),('Rajshahi','Rajshahi','6000'),('Sylhet','Sylhet','3100'),('Comilla','Comilla','3500')],
        'streets': ['Gulshan Avenue','Dhanmondi Road','Mirpur Road','Banani Road','Motijheel','Agrabad'],
        'phone_prefix': '+880',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'PK': {
        'first_m': ['Muhammad','Ali','Ahmed','Hassan','Usman','Bilal','Hamza','Abdullah','Omar','Zain'],
        'first_f': ['Fatima','Ayesha','Zainab','Maryam','Amina','Hira','Sana','Madiha','Nadia','Sara'],
        'last': ['Khan','Ahmed','Ali','Malik','Hussain','Shah','Butt','Iqbal','Raza','Qureshi'],
        'cities': [('Karachi','Sindh','74000'),('Lahore','Punjab','54000'),('Islamabad','ICT','44000'),('Rawalpindi','Punjab','46000'),('Faisalabad','Punjab','38000'),('Peshawar','KPK','25000')],
        'streets': ['Mall Road','Jinnah Avenue','Shahrah-e-Faisal','GT Road','Murree Road','University Road'],
        'phone_prefix': '+92',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'LK': {
        'first_m': ['Kavindu','Sahan','Tharindu','Dinesh','Nuwan','Chamara','Asanka','Lakshan','Dimuth','Charith'],
        'first_f': ['Sachini','Tharushi','Nethmi','Dilhani','Anusha','Chamari','Iresha','Sanduni','Wasana','Nadeesha'],
        'last': ['Perera','Fernando','Silva','De Silva','Jayawardena','Wickramasinghe','Bandara','Gunasekara','Rajapaksa','Dissanayake'],
        'cities': [('Colombo','Western','00100'),('Kandy','Central','20000'),('Galle','Southern','80000'),('Jaffna','Northern','40000'),('Negombo','Western','11500'),('Matara','Southern','81000')],
        'streets': ['Galle Road','Duplication Road','Bauddhaloka Mawatha','Havelock Road','High Street','Main Street'],
        'phone_prefix': '+94',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'MM': {
        'first_m': ['Aung','Kyaw','Min','Zaw','Myo','Htet','Htun','Naing','Win','Thiha'],
        'first_f': ['Aye','Khin','Mya','Nwe','Su','Thin','May','Hnin','Phyu','Wai'],
        'last': ['Aung','Win','Htun','Myint','Lwin','Soe','Hlaing','Oo','Tun','Zaw'],
        'cities': [('Yangon','Yangon','11181'),('Mandalay','Mandalay','05011'),('Naypyidaw','Naypyidaw','15011'),('Mawlamyine','Mon','12011'),('Bago','Bago','08011'),('Pathein','Ayeyarwady','10011')],
        'streets': ['Sule Pagoda Road','Bogyoke Aung San Road','Anawrahta Road','Strand Road','Pyay Road','Kaba Aye Pagoda Road'],
        'phone_prefix': '+95',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'KH': {
        'first_m': ['Sokha','Vannak','Vibol','Chhay','Dara','Pheakdey','Bunna','Mony','Rith','Veasna'],
        'first_f': ['Sophea','Channary','Sreymom','Bopha','Mealea','Srey','Kunthea','Theary','Chariya','Pisey'],
        'last': ['Chea','Sok','Kim','Chan','Sor','Phan','Heng','Keo','Ly','Nhem'],
        'cities': [('Phnom Penh','Phnom Penh','12000'),('Siem Reap','Siem Reap','17000'),('Battambang','Battambang','02000'),('Sihanoukville','Preah Sihanouk','18000'),('Kampong Cham','Kampong Cham','03000')],
        'streets': ['Preah Monivong Boulevard','Norodom Boulevard','Preah Sihanouk Boulevard','Street 63','Sisowath Quay','Street 278'],
        'phone_prefix': '+855',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'NP': {
        'first_m': ['Aarav','Arjun','Bibek','Bishal','Dipak','Krishna','Manish','Prakash','Rajesh','Suraj'],
        'first_f': ['Aakriti','Anjali','Kriti','Manisha','Nisha','Pooja','Priya','Sabina','Sita','Sunita'],
        'last': ['Sharma','Thapa','Gurung','Tamang','Magar','Rai','Shrestha','Basnet','Karki','Lama'],
        'cities': [('Kathmandu','Bagmati','44600'),('Pokhara','Gandaki','33700'),('Lalitpur','Bagmati','44700'),('Bharatpur','Bagmati','44200'),('Biratnagar','Province 1','56613'),('Birgunj','Madhesh','44300')],
        'streets': ['Durbar Marg','New Road','Thamel','Kantipath','Lazimpat','Putalisadak'],
        'phone_prefix': '+977',
        'phone_len': 10,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'KE': {
        'first_m': ['Brian','Kevin','David','James','John','Peter','Joseph','Daniel','Samuel','George'],
        'first_f': ['Faith','Grace','Mercy','Joy','Hope','Agnes','Mary','Esther','Rose','Gladys'],
        'last': ['Kamau','Mwangi','Ochieng','Otieno','Kipchoge','Korir','Wanjiku','Njoroge','Kimani','Mutua'],
        'cities': [('Nairobi','Nairobi','00100'),('Mombasa','Coast','80100'),('Kisumu','Nyanza','40100'),('Nakuru','Rift Valley','20100'),('Eldoret','Rift Valley','30100'),('Thika','Central','01000')],
        'streets': ['Kenyatta Avenue','Moi Avenue','Uhuru Highway','Tom Mboya Street','Haile Selassie Avenue','Kimathi Street'],
        'phone_prefix': '+254',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'GH': {
        'first_m': ['Kwame','Kofi','Kwesi','Yaw','Kwaku','Nana','Ebo','Kojo','Kwadwo','Fiifi'],
        'first_f': ['Ama','Akua','Abena','Adwoa','Afia','Efua','Akosua','Adjoa','Yaa','Afua'],
        'last': ['Mensah','Asante','Owusu','Boateng','Agyeman','Osei','Adjei','Amoah','Baidoo','Darko'],
        'cities': [('Accra','Greater Accra','GA001'),('Kumasi','Ashanti','AK001'),('Tamale','Northern','NT001'),('Takoradi','Western','WR001'),('Cape Coast','Central','CR001'),('Sunyani','Bono','BA001')],
        'streets': ['Oxford Street','Liberation Road','Ring Road','Independence Avenue','High Street','Kwame Nkrumah Avenue'],
        'phone_prefix': '+233',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'TZ': {
        'first_m': ['Baraka','Juma','Hassan','Said','Emmanuel','John','Joseph','Michael','Peter','James'],
        'first_f': ['Amina','Zainab','Rehema','Neema','Zawadi','Halima','Mariam','Grace','Happiness','Peace'],
        'last': ['Mwakasege','Kimaro','Moshi','Mwanga','Massawe','Shirima','Lyimo','Swai','Urassa','Mfinanga'],
        'cities': [('Dar es Salaam','Dar es Salaam','11101'),('Dodoma','Dodoma','41101'),('Mwanza','Mwanza','33101'),('Arusha','Arusha','23101'),('Zanzibar','Zanzibar','71101'),('Mbeya','Mbeya','53101')],
        'streets': ['Samora Avenue','Ali Hassan Mwinyi Road','Bagamoyo Road','Morogoro Road','Nyerere Road','Uhuru Street'],
        'phone_prefix': '+255',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'UG': {
        'first_m': ['Brian','Ivan','Ronald','Joseph','David','Moses','Samuel','Patrick','Robert','Alex'],
        'first_f': ['Grace','Mercy','Faith','Peace','Joy','Patience','Sarah','Esther','Mary','Prossy'],
        'last': ['Mukasa','Ssemakula','Namugera','Katende','Ochieng','Tumusiime','Byaruhanga','Namutebi','Kiggundu','Nsubuga'],
        'cities': [('Kampala','Central','10101'),('Entebbe','Central','10102'),('Jinja','Eastern','20101'),('Mbarara','Western','40101'),('Gulu','Northern','30101'),('Mbale','Eastern','25101')],
        'streets': ['Kampala Road','Bombo Road','Jinja Road','Entebbe Road','Kira Road','Parliament Avenue'],
        'phone_prefix': '+256',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'MA': {
        'first_m': ['Mohammed','Youssef','Adam','Hamza','Amine','Omar','Ayoub','Ilyass','Rachid','Karim'],
        'first_f': ['Fatima','Khadija','Meriem','Salma','Amina','Zineb','Houda','Nadia','Hind','Hanane'],
        'last': ['El Amrani','Benali','Idrissi','El Fassi','Berrada','Chraibi','Benjelloun','Tazi','El Alaoui','Kettani'],
        'cities': [('Casablanca','Casablanca-Settat','20000'),('Rabat','Rabat-Sale','10000'),('Marrakech','Marrakech-Safi','40000'),('Fes','Fes-Meknes','30000'),('Tangier','Tanger-Tetouan','90000'),('Agadir','Souss-Massa','80000')],
        'streets': ['Boulevard Mohammed V','Avenue Hassan II','Rue de la Liberte','Boulevard Zerktouni','Avenue des FAR','Rue Moulay Ismail'],
        'phone_prefix': '+212',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.fr','hotmail.com','outlook.com'],
    },
    'DZ': {
        'first_m': ['Mohammed','Ahmed','Youcef','Amine','Riad','Karim','Zakaria','Bilal','Sofiane','Ismail'],
        'first_f': ['Fatima','Amina','Khadidja','Sara','Meriem','Nour','Rania','Imane','Lina','Yasmine'],
        'last': ['Benali','Bouzid','Khelif','Hamdi','Boudiaf','Mebarki','Taleb','Saidi','Brahimi','Amrani'],
        'cities': [('Algiers','Algiers','16000'),('Oran','Oran','31000'),('Constantine','Constantine','25000'),('Annaba','Annaba','23000'),('Blida','Blida','09000'),('Setif','Setif','19000')],
        'streets': ['Rue Didouche Mourad','Boulevard Che Guevara','Rue Larbi Ben Mhidi','Boulevard Mohamed V','Rue Hassiba Ben Bouali','Rue Abane Ramdane'],
        'phone_prefix': '+213',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.fr','hotmail.com','outlook.com'],
    },
    'QA': {
        'first_m': ['Mohammed','Ahmed','Ali','Khalid','Hamad','Abdullah','Nasser','Fahad','Saad','Mansoor'],
        'first_f': ['Fatima','Maryam','Aisha','Noura','Hessa','Sara','Latifa','Mozah','Amna','Dana'],
        'last': ['Al-Thani','Al-Attiyah','Al-Kuwari','Al-Marri','Al-Sulaiti','Al-Naimi','Al-Buainain','Al-Dosari','Al-Emadi','Al-Hajri'],
        'cities': [('Doha','Doha','00000'),('Al Wakrah','Al Wakrah','00000'),('Al Khor','Al Khor','00000'),('Al Rayyan','Al Rayyan','00000'),('Lusail','Lusail','00000'),('Umm Salal','Umm Salal','00000')],
        'streets': ['Corniche Street','Al Sadd Street','Salwa Road','Al Waab Street','Khalifa Street','Pearl Boulevard'],
        'phone_prefix': '+974',
        'phone_len': 8,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.com'],
    },
    'KW': {
        'first_m': ['Mohammed','Ahmed','Abdullah','Ali','Hamad','Faisal','Khalid','Bader','Salem','Nasser'],
        'first_f': ['Fatima','Mariam','Noura','Sara','Dalal','Haya','Lulwa','Reem','Dana','Anfal'],
        'last': ['Al-Sabah','Al-Mutairi','Al-Rashidi','Al-Ajmi','Al-Shammari','Al-Azmi','Al-Enezi','Al-Harbi','Al-Otaibi','Al-Dousari'],
        'cities': [('Kuwait City','Capital','13001'),('Hawalli','Hawalli','32001'),('Salmiya','Hawalli','22001'),('Farwaniya','Farwaniya','81001'),('Jahra','Jahra','01001'),('Ahmadi','Ahmadi','64001')],
        'streets': ['Arabian Gulf Street','Fahad Al-Salem Street','Al Soor Street','Mubarak Al-Kabeer Street','Salem Al-Mubarak Street','Tunis Street'],
        'phone_prefix': '+965',
        'phone_len': 8,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.com'],
    },
    'BH': {
        'first_m': ['Mohammed','Ahmed','Ali','Hassan','Hussain','Khalid','Abdullah','Salman','Yousif','Ibrahim'],
        'first_f': ['Fatima','Mariam','Zainab','Aisha','Huda','Sara','Noor','Zahra','Maryam','Layla'],
        'last': ['Al-Khalifa','Al-Doseri','Rajab','Bucheeri','Janahi','Al-Asfoor','Ebrahim','Al-Qassab','Fakhroo','Hasan'],
        'cities': [('Manama','Capital','00000'),('Muharraq','Muharraq','00000'),('Riffa','Southern','00000'),('Hamad Town','Northern','00000'),('Isa Town','Central','00000'),('Sitra','Central','00000')],
        'streets': ['Government Avenue','Exhibition Road','King Faisal Highway','Shaikh Hamad Causeway','Al Fateh Highway','Palace Avenue'],
        'phone_prefix': '+973',
        'phone_len': 8,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.com'],
    },
    'OM': {
        'first_m': ['Mohammed','Ahmed','Ali','Said','Khalid','Abdullah','Salim','Hamad','Hamed','Nasser'],
        'first_f': ['Fatima','Maryam','Aisha','Khadija','Zainab','Asma','Balqees','Thuraya','Huda','Intisar'],
        'last': ['Al-Balushi','Al-Lawati','Al-Habsi','Al-Kindi','Al-Busaidi','Al-Harthi','Al-Riyami','Al-Rawahi','Al-Maskari','Al-Farsi'],
        'cities': [('Muscat','Muscat','100'),('Salalah','Dhofar','211'),('Sohar','Al Batinah','311'),('Nizwa','Ad Dakhiliyah','611'),('Sur','Ash Sharqiyah','411'),('Ibri','Ad Dhahirah','511')],
        'streets': ['Sultan Qaboos Street','Al Qurum Street','Muttrah Corniche','Ruwi High Street','Way No 1','Al Nahda Street'],
        'phone_prefix': '+968',
        'phone_len': 8,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.com'],
    },
    'JO': {
        'first_m': ['Mohammed','Ahmad','Omar','Khaled','Abdullah','Ali','Yousef','Fadi','Sami','Tariq'],
        'first_f': ['Lina','Rania','Dana','Hala','Maha','Rana','Dina','Nour','Layla','Zeina'],
        'last': ['Al-Smadi','Haddad','Mansour','Obeidat','Batayneh','Tarawneh','Rawashdeh','Ababneh','Maaitah','Zoubi'],
        'cities': [('Amman','Amman','11110'),('Zarqa','Zarqa','13110'),('Irbid','Irbid','21110'),('Aqaba','Aqaba','77110'),('Madaba','Madaba','17110'),('Salt','Balqa','19110')],
        'streets': ['King Abdullah Street','Rainbow Street','Mecca Street','Zahran Street','University Street','Gardens Street'],
        'phone_prefix': '+962',
        'phone_len': 9,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','outlook.com'],
    },
    'LB': {
        'first_m': ['Georges','Michel','Antoine','Pierre','Joseph','Ali','Hassan','Hussein','Elie','Walid'],
        'first_f': ['Nour','Maya','Lea','Sarah','Lara','Rita','Nadine','Rima','Zeina','Carla'],
        'last': ['Khoury','Haddad','Saad','Habib','Hariri','Aoun','Gemayel','Nasrallah','Salam','Frangieh'],
        'cities': [('Beirut','Beirut','1100'),('Tripoli','North','1300'),('Sidon','South','1600'),('Jounieh','Mount Lebanon','1200'),('Zahle','Beqaa','1800'),('Byblos','Mount Lebanon','1401')],
        'streets': ['Hamra Street','Rue Gouraud','Bliss Street','Charles Malek Avenue','Maarad Street','Rue Weygand'],
        'phone_prefix': '+961',
        'phone_len': 8,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.com'],
    },
    'UY': {
        'first_m': ['Santiago','Mateo','Benjamin','Thiago','Nicolas','Martin','Sebastian','Joaquin','Lucas','Agustin'],
        'first_f': ['Sofia','Valentina','Martina','Isabella','Emilia','Catalina','Mia','Camila','Luciana','Emma'],
        'last': ['Rodriguez','Gonzalez','Martinez','Lopez','Perez','Garcia','Fernandez','Silva','Santos','Diaz'],
        'cities': [('Montevideo','Montevideo','11000'),('Salto','Salto','50000'),('Paysandu','Paysandu','60000'),('Las Piedras','Canelones','15000'),('Rivera','Rivera','40000'),('Maldonado','Maldonado','20000')],
        'streets': ['18 de Julio','Sarandi','Rambla','Avenida Italia','Bulevar Artigas','Avenida Rivera'],
        'phone_prefix': '+598',
        'phone_len': 8,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.com'],
    },
    'EC': {
        'first_m': ['Santiago','Sebastian','Mateo','Nicolas','Daniel','Alejandro','Andres','David','Juan','Carlos'],
        'first_f': ['Sofia','Valentina','Camila','Isabella','Emilia','Maria','Daniela','Paula','Gabriela','Ana'],
        'last': ['Garcia','Rodriguez','Martinez','Lopez','Gonzalez','Torres','Ramirez','Flores','Sanchez','Morales'],
        'cities': [('Quito','Pichincha','170150'),('Guayaquil','Guayas','090150'),('Cuenca','Azuay','010150'),('Ambato','Tungurahua','180150'),('Manta','Manabi','130802'),('Machala','El Oro','070150')],
        'streets': ['Avenida Amazonas','Calle Venezuela','Avenida 10 de Agosto','Garcia Moreno','Sucre','Bolivar'],
        'phone_prefix': '+593',
        'phone_len': 9,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.com'],
    },
    'VE': {
        'first_m': ['Santiago','Sebastian','Mateo','Samuel','Daniel','Alejandro','Andres','Diego','Gabriel','Nicolas'],
        'first_f': ['Valentina','Camila','Sofia','Isabella','Mariana','Gabriela','Andrea','Daniela','Maria','Victoria'],
        'last': ['Rodriguez','Gonzalez','Hernandez','Garcia','Martinez','Lopez','Perez','Ramirez','Torres','Diaz'],
        'cities': [('Caracas','Capital','1010'),('Maracaibo','Zulia','4001'),('Valencia','Carabobo','2001'),('Barquisimeto','Lara','3001'),('Maracay','Aragua','2101'),('Ciudad Guayana','Bolivar','8050')],
        'streets': ['Avenida Libertador','Avenida Bolivar','Calle Carabobo','Avenida Urdaneta','Boulevard Sabana Grande','Avenida Francisco de Miranda'],
        'phone_prefix': '+58',
        'phone_len': 10,
        'email_domains': ['gmail.com','hotmail.com','yahoo.com','outlook.com'],
    },
    'LT': {
        'first_m': ['Lukas','Matas','Nojus','Dominykas','Kajus','Benas','Gustas','Emilis','Danielius','Adomas'],
        'first_f': ['Emilija','Gabija','Kamile','Ugne','Liepa','Agne','Guste','Viktorija','Ieva','Austeja'],
        'last': ['Kazlauskas','Jonaitis','Petrauskas','Stankevicius','Jankauskas','Butkus','Paulauskas','Urbonas','Kavaliauskas','Vasiliauskas'],
        'cities': [('Vilnius','Vilnius','01001'),('Kaunas','Kaunas','44001'),('Klaipeda','Klaipeda','91001'),('Siauliai','Siauliai','76001'),('Panevezys','Panevezys','35001'),('Alytus','Alytus','62001')],
        'streets': ['Gedimino Prospektas','Pilies Gatve','Vilniaus Gatve','Laisves Aleja','Savanoriu Prospektas','Ukmerges Gatve'],
        'phone_prefix': '+370',
        'phone_len': 8,
        'email_domains': ['gmail.com','yahoo.com','hotmail.com','inbox.lt'],
    },
    'LV': {
        'first_m': ['Arturs','Daniels','Roberts','Emils','Markuss','Kristians','Olivers','Gustavs','Ralfs','Toms'],
        'first_f': ['Sofija','Emilija','Marta','Anna','Alise','Eva','Darja','Laura','Eliza','Karlina'],
        'last': ['Berzins','Ozolins','Jansons','Petersons','Kalnins','Zariņs','Liepins','Krumins','Ozols','Vitols'],
        'cities': [('Riga','Riga','LV-1001'),('Daugavpils','Latgale','LV-5401'),('Liepaja','Kurzeme','LV-3401'),('Jelgava','Zemgale','LV-3001'),('Jurmala','Pieriga','LV-2015'),('Ventspils','Kurzeme','LV-3601')],
        'streets': ['Brivibas iela','Valdemara iela','Elizabetes iela','Merkela iela','Gertrudes iela','Terbatas iela'],
        'phone_prefix': '+371',
        'phone_len': 8,
        'email_domains': ['gmail.com','inbox.lv','yahoo.com','outlook.com'],
    },
    'EE': {
        'first_m': ['Robin','Rasmus','Oliver','Hugo','Markus','Martin','Karl','Erik','Artur','Mattias'],
        'first_f': ['Sofia','Maria','Mia','Hanna','Emily','Emma','Laura','Anna','Lenna','Liisa'],
        'last': ['Tamm','Saar','Sepp','Magi','Kask','Kukk','Rebane','Ilves','Parts','Luik'],
        'cities': [('Tallinn','Harju','10111'),('Tartu','Tartu','50050'),('Narva','Ida-Viru','20303'),('Parnu','Parnu','80010'),('Viljandi','Viljandi','71003'),('Rakvere','Lääne-Viru','44305')],
        'streets': ['Viru','Pikk','Narva maantee','Parnu maantee','Vabaduse valjak','Gonsiori'],
        'phone_prefix': '+372',
        'phone_len': 8,
        'email_domains': ['gmail.com','hot.ee','mail.ee','outlook.com'],
    },
    'IS': {
        'first_m': ['Jon','Gudmundur','Olafur','Sigurdur','Gunnar','Kristjan','Magnus','Stefan','Arnar','Bjarni'],
        'first_f': ['Gudrun','Sigridur','Kristin','Margret','Helga','Anna','Jonina','Olof','Katrin','Vigdis'],
        'last': ['Jonsson','Sigurdsson','Gudmundsson','Gunnarsson','Olafsson','Kristjansson','Magnusson','Stefansson','Arnarson','Bjarnason'],
        'cities': [('Reykjavik','Capital','101'),('Kopavogur','Capital','200'),('Hafnarfjordur','Capital','220'),('Akureyri','Northeast','600'),('Keflavik','Southern Peninsula','230'),('Selfoss','South','800')],
        'streets': ['Laugavegur','Bankastræti','Skolavordustigur','Hverfisgata','Austurstræti','Adalstræti'],
        'phone_prefix': '+354',
        'phone_len': 7,
        'email_domains': ['gmail.com','simnet.is','outlook.com','hotmail.com'],
    },
    'LU': {
        'first_m': ['Luca','Noah','Ben','Max','Louis','Liam','Tom','Leo','Alexander','Felix'],
        'first_f': ['Marie','Emma','Lea','Lena','Sophie','Anna','Sarah','Laura','Mia','Lisa'],
        'last': ['Muller','Weber','Schmit','Hoffmann','Wagner','Klein','Schneider','Thill','Schiltz','Kieffer'],
        'cities': [('Luxembourg City','Luxembourg','1009'),('Esch-sur-Alzette','Sud','4001'),('Differdange','Sud','4501'),('Dudelange','Sud','3401'),('Ettelbruck','Nord','9001'),('Diekirch','Nord','9201')],
        'streets': ['Grand-Rue','Avenue de la Gare','Route de Longwy','Rue Philippe II','Boulevard Royal','Rue du Fosse'],
        'phone_prefix': '+352',
        'phone_len': 9,
        'email_domains': ['gmail.com','pt.lu','outlook.com','hotmail.com'],
    },
    'CY': {
        'first_m': ['Andreas','Georgios','Christos','Nicos','Michalis','Panayiotis','Petros','Stelios','Costas','Antonis'],
        'first_f': ['Maria','Elena','Christina','Georgia','Sophia','Anna','Irene','Katerina','Eleni','Demetra'],
        'last': ['Papadopoulos','Christodoulou','Ioannou','Georgiou','Constantinou','Nicolaou','Antoniou','Petrou','Loizou','Andreou'],
        'cities': [('Nicosia','Nicosia','1016'),('Limassol','Limassol','3036'),('Larnaca','Larnaca','6023'),('Paphos','Paphos','8021'),('Paralimni','Famagusta','5280'),('Strovolos','Nicosia','2018')],
        'streets': ['Makarios Avenue','Ledra Street','Grivas Digenis Avenue','Anexartisias Street','Arch. Kyprianos Street','Stasinou Avenue'],
        'phone_prefix': '+357',
        'phone_len': 8,
        'email_domains': ['gmail.com','cytanet.com.cy','outlook.com','yahoo.com'],
    },
    'MT': {
        'first_m': ['Luke','Matthew','Jake','Liam','Gabriel','Noah','Nathan','Matteo','Isaac','Samuel'],
        'first_f': ['Emma','Mia','Julia','Ella','Hannah','Martina','Amy','Emily','Sophie','Nicole'],
        'last': ['Borg','Camilleri','Vella','Farrugia','Zammit','Galea','Grech','Micallef','Attard','Spiteri'],
        'cities': [('Valletta','South Eastern','VLT'),('Sliema','Northern Harbour','SLM'),('St Julians','Northern Harbour','STJ'),('Birkirkara','Northern Harbour','BKR'),('Mosta','Northern','MST'),('Qormi','South Eastern','QRM')],
        'streets': ['Republic Street','Tower Road','Bisazza Street','Main Street','Manwel Dimech Street','St Anne Street'],
        'phone_prefix': '+356',
        'phone_len': 8,
        'email_domains': ['gmail.com','onvol.net','outlook.com','yahoo.com'],
    },
    'SI': {
        'first_m': ['Luka','Nik','Jan','Filip','Zan','Mark','Tim','Nejc','Jaka','Matic'],
        'first_f': ['Eva','Lara','Nika','Zala','Ana','Maja','Sara','Ema','Hana','Nina'],
        'last': ['Novak','Horvat','Krajnc','Kovac','Zupan','Potocnik','Vidmar','Kralj','Golob','Korošec'],
        'cities': [('Ljubljana','Central','1000'),('Maribor','Podravje','2000'),('Celje','Savinjska','3000'),('Kranj','Gorenjska','4000'),('Koper','Obalno-kraska','6000'),('Novo Mesto','Jugovzhodna','8000')],
        'streets': ['Presernov trg','Cankarjeva','Gosposvetska','Slovenska cesta','Miklošičeva','Čopova'],
        'phone_prefix': '+386',
        'phone_len': 8,
        'email_domains': ['gmail.com','siol.net','outlook.com','yahoo.com'],
    },
}

COUNTRY_CODE_MAP = {
    'UNITED STATES': 'US', 'USA': 'US', 'UNITED KINGDOM': 'UK', 'GREAT BRITAIN': 'UK', 'GB': 'UK',
    'CANADA': 'CA', 'AUSTRALIA': 'AU', 'GERMANY': 'DE', 'FRANCE': 'FR', 'INDIA': 'IN',
    'BRAZIL': 'BR', 'MEXICO': 'MX', 'JAPAN': 'JP', 'ITALY': 'IT', 'SPAIN': 'ES',
    'RUSSIA': 'RU', 'RUSSIAN FEDERATION': 'RU', 'CHINA': 'CN', 'SOUTH KOREA': 'KR',
    'KOREA, REPUBLIC OF': 'KR', 'REPUBLIC OF KOREA': 'KR',
    'NETHERLANDS': 'NL', 'SWEDEN': 'SE', 'NORWAY': 'NO', 'DENMARK': 'DK', 'FINLAND': 'FI',
    'SWITZERLAND': 'CH', 'AUSTRIA': 'AT', 'BELGIUM': 'BE', 'PORTUGAL': 'PT',
    'IRELAND': 'IE', 'POLAND': 'PL', 'CZECH REPUBLIC': 'CZ', 'CZECHIA': 'CZ',
    'TURKEY': 'TR', 'TURKIYE': 'TR', 'ARGENTINA': 'AR', 'CHILE': 'CL',
    'COLOMBIA': 'CO', 'PERU': 'PE', 'PHILIPPINES': 'PH',
    'INDONESIA': 'ID', 'THAILAND': 'TH', 'VIETNAM': 'VN', 'VIET NAM': 'VN',
    'MALAYSIA': 'MY', 'SINGAPORE': 'SG', 'HONG KONG': 'HK',
    'TAIWAN': 'TW', 'TAIWAN, PROVINCE OF CHINA': 'TW',
    'NEW ZEALAND': 'NZ', 'SOUTH AFRICA': 'ZA',
    'NIGERIA': 'NG', 'EGYPT': 'EG', 'SAUDI ARABIA': 'SA',
    'UAE': 'AE', 'UNITED ARAB EMIRATES': 'AE', 'ISRAEL': 'IL',
    'GREECE': 'GR', 'ROMANIA': 'RO', 'HUNGARY': 'HU', 'UKRAINE': 'UA',
    'CROATIA': 'HR', 'BULGARIA': 'BG', 'SLOVAKIA': 'SK', 'SLOVAK REPUBLIC': 'SK',
    'SERBIA': 'RS', 'BANGLADESH': 'BD', 'PAKISTAN': 'PK', 'SRI LANKA': 'LK',
    'MYANMAR': 'MM', 'BURMA': 'MM', 'CAMBODIA': 'KH', 'NEPAL': 'NP',
    'KENYA': 'KE', 'GHANA': 'GH', 'TANZANIA': 'TZ', 'UNITED REPUBLIC OF TANZANIA': 'TZ',
    'UGANDA': 'UG', 'MOROCCO': 'MA', 'ALGERIA': 'DZ',
    'QATAR': 'QA', 'KUWAIT': 'KW', 'BAHRAIN': 'BH', 'OMAN': 'OM',
    'JORDAN': 'JO', 'LEBANON': 'LB',
    'URUGUAY': 'UY', 'ECUADOR': 'EC', 'VENEZUELA': 'VE',
    'LITHUANIA': 'LT', 'LATVIA': 'LV', 'ESTONIA': 'EE',
    'ICELAND': 'IS', 'LUXEMBOURG': 'LU', 'CYPRUS': 'CY', 'MALTA': 'MT', 'SLOVENIA': 'SI',
}


def _resolve_country_code(country_name, country_code):
    if country_code and country_code in NAMES_BY_COUNTRY:
        return country_code
    if country_name:
        upper = country_name.upper().strip()
        if upper in COUNTRY_CODE_MAP:
            code = COUNTRY_CODE_MAP[upper]
            if code in NAMES_BY_COUNTRY:
                return code
        if upper in NAMES_BY_COUNTRY:
            return upper
    return 'US'


def generate_holder_info(country_name='', country_code=''):
    code = _resolve_country_code(country_name, country_code)
    data = NAMES_BY_COUNTRY.get(code, NAMES_BY_COUNTRY['US'])

    gender = random.choice(['m', 'f'])
    first = random.choice(data[f'first_{gender}'])
    last = random.choice(data['last'])
    full_name = f"{first} {last}"

    username_base = f"{first.lower()}{last.lower()}{random.randint(1, 999)}"
    email = f"{username_base}@{random.choice(data['email_domains'])}"

    digits = ''.join([str(random.randint(0, 9)) for _ in range(data['phone_len'])])
    if digits[0] == '0':
        digits = str(random.randint(1, 9)) + digits[1:]
    phone = f"{data['phone_prefix']}{digits}"

    city, state, zipcode = random.choice(data['cities'])
    street_num = random.randint(1, 9999)
    street = random.choice(data['streets'])
    if code == 'JP':
        address = f"{street}, {city}, {state} {zipcode}"
    else:
        address = f"{street_num} {street}, {city}, {state} {zipcode}"

    return {
        'name': full_name,
        'email': email,
        'phone': phone,
        'address': address,
        'city': city,
        'state': state,
        'zip': zipcode,
        'country_code': code
    }
