// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/onichan-hero/BottomLeftCard.tsx": () => import("../components/mockups/onichan-hero/BottomLeftCard.tsx"),
  "./components/mockups/onichan-hero/BottomRightCorner.tsx": () => import("../components/mockups/onichan-hero/BottomRightCorner.tsx"),
  "./components/mockups/onichan-hero/Hero.tsx": () => import("../components/mockups/onichan-hero/Hero.tsx"),
  "./components/mockups/onichan-hero/HeroBadge.tsx": () => import("../components/mockups/onichan-hero/HeroBadge.tsx"),
  "./components/mockups/onichan-hero/Navbar.tsx": () => import("../components/mockups/onichan-hero/Navbar.tsx")
};
